### PR TITLE
Add a property to the tracker history for all queries

### LINKED ISSUE #32: Add a property to the tracker history to track all queries in order
Currently, the tracker history is split up by method (e.g. `tracker.history.select`, `tracker.history.insert`). It appears to me that there's no built-in way to get a list of all queries in the order that they were run.

I think it would make sense to add something like `tracker.history.all`, which would be a list of all queries.

### PR DESCRIPTION
**Pull request by aryehb**
Closes #32

### CODE REVIEW

**Comment by felixmosh** [comment]
Thank you for the PR.
There is `any` which does the same thing...i think that will confuse people.

**Comment by Fryuni** [comment]
The difference is that `history.any` only holds queries matched using the `on.any` while `history.all` would have every query regardless of how it was matched.

For example:
```ts
tracker.on.insert('table_name').responseOnce(1);
tracker.on.update('table_name').responseOnce(1);

await knex.insert({id: 1, value: 1}).into('table_name').on_conflict('merge');

await knex.update({value: knex.raw('"value" + 1')}).from('table_name').where('id', 1);

// Contains only the insert
console.log(tracker.history.insert);

// Contains only the update
console.log(tracker.history.update);

// This one is empty
console.log(tracker.history.any);

// How to ensure that the update happened before the upsert?
```

**Comment by felixmosh** [comment]
For these places which you want to check order of exec, use the any matcher... Is it not enough?

**Comment by Fryuni** [comment]
Well... sure:
```ts
tracker.on.insert('table_name').responseOnce(1);
tracker.on.update('table_name').responseOnce(1);

// Could be replaced with
tracker.on.any(query => query.method === 'insert' && query.sql.includes('table_name')).responseOnce(1);
tracker.on.any(query => query.method === 'delete' && query.sql.includes('table_name')).responseOnce(1);
```

But this seems unnecessarily verbose.

**Comment by felixmosh** [comment]
Ok, You've convinced me, @aryehb let's fix the small things that I've mentioned, and we will merge it :]

**Comment by aryehb** [comment]
@felixmosh I rebased and added the `resetHistory()` behavior, along with some tests. Let me know if there's any other tests you want me to add.

**Comment by felixmosh** [comment]
Thank you for this PR 🙏🏼

**Pull request merged**
